apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: network-backups
  namespace: network-platform

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: local-path

  resources:
    requests:
      storage: 5Gi
