apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-worker
  namespace: network-platform

spec:
  replicas: 1

  selector:
    matchLabels:
      app: network-worker

  template:
    metadata:
      labels:
        app: network-worker

    spec:
      serviceAccountName: network-automation-worker

      imagePullSecrets:
        - name: ghcr-secret

      securityContext:
        fsGroup: 10001

      containers:
        - name: network-worker
          image: ghcr.io/gurinder12345/network-worker:v0.14.5

          imagePullPolicy: IfNotPresent

          env:
            - name: CELERY_BROKER_URL
              value: redis://redis-master.network-platform.svc.cluster.local:6379/0

            - name: VAULT_ADDR
              value: http://vault.security.svc:8200
             
            - name: DB_HOST
              value: postgresql.network-platform.svc.cluster.local

            - name: DB_PORT
              value: "5432"

            - name: DB_NAME
              value: networkdb

            - name: DB_USER
              value: networkapp

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-auth
                  key: password

          volumeMounts:
            - name: backups
              mountPath: /backups

      volumes:
        - name: backups
          persistentVolumeClaim:
            claimName: network-backups
