apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-worker
  namespace: network-platform

spec:
  replicas: 1

  selector:
    matchLabels:
      app: network-worker

  template:
    metadata:
      labels:
        app: network-worker

    spec:
      serviceAccountName: network-automation-worker

      imagePullSecrets:
        - name: ghcr-secret

      containers:
        - name: network-worker
          image: ghcr.io/gurinder12345/network-worker:v0.4.2
          imagePullPolicy: IfNotPresent

          env:
            - name: CELERY_BROKER_URL
              value: redis://redis-master.network-platform.svc.cluster.local:6379/0

            - name: VAULT_ADDR
              value: http://vault.security.svc:8200
