apiVersion: v1
kind: Service
metadata:
  name: network-api
  namespace: network-platform
  labels:
    app: network-api

spec:
  type: ClusterIP

  selector:
    app: network-api

  ports:
    - name: http
      port: 8081
      targetPort: 8081
