apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-apps
  namespace: argocd

spec:
  generators:
    - list:
        elements:
          - name: hello-app
            path: kubernetes/apps/hello-app
            namespace: network-platform
          - name: network-automation-worker
            path: kubernetes/network-platform/serviceaccounts
            namespace: network-platform

  template:
    metadata:
      name: "{{name}}"

    spec:
      project: network-platform

      source:
        repoURL: "https://github.com/Gurinder12345/Network-Dashboard.git"
        targetRevision: HEAD
        path: "{{path}}"

      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
