apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: security-apps
  namespace: argocd

spec:
  generators:
    - list:
        elements:
          - name: vault
            namespace: security
            chart: vault
            repoURL: https://helm.releases.hashicorp.com
            revision: "0.34.1"

  template:
    metadata:
      name: "{{name}}"

    spec:
      project: network-platform

      source:
        repoURL: "{{repoURL}}"
        chart: "{{chart}}"
        targetRevision: "{{revision}}"

        helm:
          releaseName: vault

          values: |
            injector:
              enabled: false

            ui:
              enabled: true

            server:
              standalone:
                enabled: true

              ha:
                enabled: false

              dataStorage:
                enabled: true
                size: 10Gi
                storageClass: local-path

              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
                limits:
                  cpu: 500m
                  memory: 1Gi

      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true

        syncOptions:
          - CreateNamespace=false
